// <auto-generated />
using System;
using EUseControl.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EUseControl.DataAccess.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ServiceDataSpecialistData", b =>
                {
                    b.Property<string>("ServicesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialistDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("ServicesId", "SpecialistDataId");

                    b.HasIndex("SpecialistDataId");

                    b.ToTable("ServiceDataSpecialistData");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.Specialist.SpecialistData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Specialists");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.Specialist.SpecialistReview", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ClientId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.Specialist.SpecialistWorkSchedule", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialistId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.User.ULoginData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginDataTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginIp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserIp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.User.UserData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.services.ServiceBookingData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.services.ServiceCategoryData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameOfCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.services.ServiceData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionOfService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationOfService")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameOfMaster")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfService")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceOfService")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ServiceCategoryDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ServiceCategoryDataId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.services.ServiceImgData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceImages");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.services.ServiceTimeSlot", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialistId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("ServiceDataSpecialistData", b =>
                {
                    b.HasOne("eUseControl.Domain.Entities.services.ServiceData", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eUseControl.Domain.Entities.Specialist.SpecialistData", null)
                        .WithMany()
                        .HasForeignKey("SpecialistDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.Specialist.SpecialistReview", b =>
                {
                    b.HasOne("eUseControl.Domain.Entities.services.ServiceBookingData", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.HasOne("eUseControl.Domain.Entities.User.UserData", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.Specialist.SpecialistWorkSchedule", b =>
                {
                    b.HasOne("eUseControl.Domain.Entities.Specialist.SpecialistData", "SpecialistData")
                        .WithMany()
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecialistData");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.services.ServiceBookingData", b =>
                {
                    b.HasOne("eUseControl.Domain.Entities.User.UserData", null)
                        .WithMany("ServiceBookingData")
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.services.ServiceData", b =>
                {
                    b.HasOne("eUseControl.Domain.Entities.services.ServiceCategoryData", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eUseControl.Domain.Entities.services.ServiceCategoryData", null)
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryDataId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.services.ServiceImgData", b =>
                {
                    b.HasOne("eUseControl.Domain.Entities.services.ServiceData", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.services.ServiceTimeSlot", b =>
                {
                    b.HasOne("eUseControl.Domain.Entities.services.ServiceBookingData", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.HasOne("eUseControl.Domain.Entities.Specialist.SpecialistData", null)
                        .WithMany("TimeSlots")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.Specialist.SpecialistData", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.User.UserData", b =>
                {
                    b.Navigation("ServiceBookingData");
                });

            modelBuilder.Entity("eUseControl.Domain.Entities.services.ServiceCategoryData", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
